version: "3"
services:
  expenses-db:
    image: mysql:8.0.31
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "3306:3306"
    env_file: docker-compose.env
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./expenses/expenses-db:/var/lib/mysql
  expenses-be:
    image: expenses-be
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
    env_file: docker-compose.env
    depends_on:
      - expenses-db
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./expenses/:/expenses
      - ./expenses/log:/log
  expenses-ui:
    image: expenses-ui
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "80:80"
    env_file: docker-compose.env
    depends_on:
      - expenses-be
    volumes:
      - ./localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
